### ISSUE TITLE
Luisa_T._Buchman.jpg

### ISSUE THREAD

**Issue by luisabuchman** [moble/www_black-holes_org#30]
![Luisa_T _Buchman](https://github.com/user-attachments/assets/af7612c9-cfe3-4fd3-942c-8415642040d9)

**Comment by duetosymmetry** [comment]
I think this is supposed to be part of PR #31 instead of an issue. Can I close this issue?

**Comment by luisabuchman** [comment]
Yes please. I had trouble with replacing my old photo in a clean way.  I have tried to squash the two commits deleting the old photo but I can't because one of them is a merge. I give you permission to do whatever you need to do to replace the old photo with the new one. I apologize for the extra work.
